[package]
name = "pathplanning"
version = "0.1.0"
authors = ["Travis Sturzl <tsturzl@lefthandrobotics.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
geo = "0.12.2"
rand = "0.7"
geo-offset = "0.1.0"
